# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- staging
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  displayName: npm ci
  inputs:
    command: 'ci'

- task: Npm@1
  displayName: npm run build
  inputs:
    command: 'custom'
    customCommand: 'run build'
