# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, staging, dev ]
  pull_request:
    branches: [ main, staging, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: npx lerna bootstrap
      - run: npx lerna run build
      #- run: lerna test
      #- name: Codacy Coverage Reporter
      #  uses: codacy/codacy-coverage-reporter-action@0.2.0
      #  with:
      #    project-token: ${{ secrets.CodacyCoverageToken }}
      #    coverage-reports: coverage/lcov.info
      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref == 'ref/head/main'
          steps:
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSPARTICLES }}'
                projectId: tsparticles
                channelId: live

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref == 'ref/head/staging'
          steps:
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSPARTICLES }}'
                projectId: tsparticles
                channelId: next

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.ref == 'ref/head/dev'
          steps:
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSPARTICLES }}'
                projectId: tsparticles
                channelId: dev

      - uses: FirebaseExtended/action-hosting-deploy@v0
        if: github.base_ref != null
          steps:
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TSPARTICLES }}'
                projectId: tsparticles
